#name: Docker Build & Push
#
#on:
#  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+*'
#    branches:
#      - master
#      - dev
#
#jobs:
#  docker-build-push:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v3
#        with:
#          images: vidanyu/ache
#          # Create docker tags for matches branches, PRs, and version tags
#          # without the 'v' prefix (e.g., '0.1.2' or '0.1.2-rc.1')
#          tags: |
#            type=ref,event=branch
#            type=ref,event=pr
#            type=match,pattern=[0-9]+\.[0-9]+\.[0-9]+.*
#
#      - name: Login to DockerHub
#        if: github.event_name != 'pull_request'
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push docker images with multi-arch support
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Dockerfile
#          platforms: linux/amd64,linux/arm64
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#
